id: P004358
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG09757
  title: འདན་མའི་ལོ་རྒྱུས་གསེར་གྱི་འོད་ཐིག་
  author: ''
  volumes:
    41285d2784ec4a0688bebfe936733d35:
      image_group_id: I00KG09839
      title: ''
      volume_number: 1
      total_pages: 228
      base_file: v001.txt
